name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd main
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd main
        pytest tests/ -v
    
    - name: Build Docker image
      run: |
        cd main
        docker build -t flask-lab-app:${{ github.sha }} .